In [1]:
import subprocess
import sys

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

install('Altair')
import pandas as pd
import altair as alt

film_scripts = pd.read_csv('cleaned_pudding_data.csv')
film_scripts

Requirement already satisfied: Altair in /Users/seanyoon/opt/anaconda3/lib/python3.9/site-packages (5.2.0)
Requirement already satisfied: numpy in /Users/seanyoon/opt/anaconda3/lib/python3.9/site-packages (from Altair) (1.21.5)
Requirement already satisfied: jsonschema>=3.0 in /Users/seanyoon/opt/anaconda3/lib/python3.9/site-packages (from Altair) (4.16.0)
Requirement already satisfied: pandas>=0.25 in /Users/seanyoon/opt/anaconda3/lib/python3.9/site-packages (from Altair) (1.4.4)
Requirement already satisfied: packaging in /Users/seanyoon/opt/anaconda3/lib/python3.9/site-packages (from Altair) (21.3)
Requirement already satisfied: toolz in /Users/seanyoon/opt/anaconda3/lib/python3.9/site-packages (from Altair) (0.11.2)
Requirement already satisfied: jinja2 in /Users/seanyoon/opt/anaconda3/lib/python3.9/site-packages (from Altair) (2.11.3)
Requirement already satisfied: typing-extensions>=4.0.1 in /Users/seanyoon/opt/anaconda3/lib/python3.9/site-packages (from Altair) (4.3.0)
Requirement already satisfied: attrs>=17.4.0 in /Users/seanyoon/opt/anaconda3/lib/python3.9/site-packages (from jsonschema>=3.0->Altair) (21.4.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /Users/seanyoon/opt/anaconda3/lib/python3.9/site-packages (from jsonschema>=3.0->Altair) (0.18.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/seanyoon/opt/anaconda3/lib/python3.9/site-packages (from pandas>=0.25->Altair) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/seanyoon/opt/anaconda3/lib/python3.9/site-packages (from pandas>=0.25->Altair) (2022.1)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/seanyoon/opt/anaconda3/lib/python3.9/site-packages (from jinja2->Altair) (2.0.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/seanyoon/opt/anaconda3/lib/python3.9/site-packages (from packaging->Altair) (3.0.9)
Requirement already satisfied: six>=1.5 in /Users/seanyoon/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas>=0.25->Altair) (1.16.0)

,imdb_id,script_id,title,year,gross (inflation-adjusted),link
0,tt0023622,5154,Trouble in Paradise,1932,NaN,http://www.aellea.com/emruf3/tip.html
1,tt0024368,4677,Mystery of the Wax Museum,1933,NaN,http://www.aellea.com/script/qWAX.htm
2,tt0025905,5147,Transatlantic Merry-Go-Round,1934,NaN,http://www.aellea.com/emruf3/tm.html
3,tt0031679,4658,Mr. Smith Goes to Washington,1939,NaN,http://www.dailyscript.com/scripts/Mr%20Smith%...
4,tt0031725,3016,Ninotchka,1939,45.0,http://www.dailyscript.com/scripts/Ninotchka.txt
...,...,...,...,...,...,...
119,tt0366627,2651,The Jacket,2005,8.0,http://www.dailyscript.com/scripts/The_Jacket....
120,tt0372532,4992,The Wedding Date,2005,42.0,http://www.dailyscript.com/scripts/somethingbo...
121,tt0416658,4034,Crazylove,2005,NaN,http://www.dailyscript.com/scripts/crazy_love....
122,tt0421054,4121,Domino,2005,13.0,http://www.dailyscript.com/scripts/domino.html
123,tt0480249,4392,I Am Legend,2007,323.0,http://www.horrorlair.com/scripts/legend.txt

In [6]:
character_list_df = pd.read_csv('character_list5.csv', encoding='ISO-8859-1')
character_mapping_df = pd.read_csv('character_mapping.csv', encoding='ISO-8859-1')
metaddata_df = pd.read_csv('meta_data7.csv', encoding='ISO-8859-1')

In [2]:
film_scripts.columns

Index(['imdb_id', 'script_id', 'title', 'year', 'gross (inflation-adjusted)',
       'link'],
      dtype='object')

In [3]:
import altair as alt

In [7]:
dialogue_df = pd.merge(character_list_df, metaddata_df, on='script_id', how="inner")
dialogue_df

,script_id,imdb_character_name,words,gender,age,imdb_id,title,year,gross,lines_data
0,280,betty,311,f,35.0,tt0112579,The Bridges of Madison County,1995,142.0,4332023434343443203433434334433434343434434344...
1,280,carolyn johnson,873,f,NaN,tt0112579,The Bridges of Madison County,1995,142.0,4332023434343443203433434334433434343434434344...
2,280,eleanor,138,f,NaN,tt0112579,The Bridges of Madison County,1995,142.0,4332023434343443203433434334433434343434434344...
3,280,francesca johns,2251,f,46.0,tt0112579,The Bridges of Madison County,1995,142.0,4332023434343443203433434334433434343434434344...
4,280,madge,190,f,46.0,tt0112579,The Bridges of Madison County,1995,142.0,4332023434343443203433434334433434343434434344...
...,...,...,...,...,...,...,...,...,...,...
23043,9254,lumiere,1063,m,56.0,tt0101414,Beauty and the Beast,1991,452.0,3245753334377767774433634446467677732244465553...
23044,9254,maurice,1107,m,71.0,tt0101414,Beauty and the Beast,1991,452.0,3245753334377767774433634446467677732244465553...
23045,9254,monsieur d'arqu,114,m,58.0,tt0101414,Beauty and the Beast,1991,452.0,3245753334377767774433634446467677732244465553...
23046,9254,mrs. potts,564,f,66.0,tt0101414,Beauty and the Beast,1991,452.0,3245753334377767774433634446467677732244465553...
23047,9254,wardrobe,121,f,54.0,tt0101414,Beauty and the Beast,1991,452.0,3245753334377767774433634446467677732244465553...

In [17]:
extended_dialogue_df = pd.merge(character_list_df, film_scripts, on='script_id', how="inner")
extended_dialogue_df

,script_id,imdb_character_name,words,gender,age,imdb_id,title,year,gross (inflation-adjusted),link
0,280,betty,311,f,35.0,tt0112579,The Bridges of Madison County,1995,142.0,http://www.awesomefilm.com/script/bomc.txt
1,280,carolyn johnson,873,f,NaN,tt0112579,The Bridges of Madison County,1995,142.0,http://www.awesomefilm.com/script/bomc.txt
2,280,eleanor,138,f,NaN,tt0112579,The Bridges of Madison County,1995,142.0,http://www.awesomefilm.com/script/bomc.txt
3,280,francesca johns,2251,f,46.0,tt0112579,The Bridges of Madison County,1995,142.0,http://www.awesomefilm.com/script/bomc.txt
4,280,madge,190,f,46.0,tt0112579,The Bridges of Madison County,1995,142.0,http://www.awesomefilm.com/script/bomc.txt
...,...,...,...,...,...,...,...,...,...,...
1402,5254,herr falkstein,158,m,69.0,tt0072431,Young Frankenstein,1974,401.0,http://www.horrorlair.com/scripts/young.txt
1403,5254,igor,1072,m,40.0,tt0072431,Young Frankenstein,1974,401.0,http://www.horrorlair.com/scripts/young.txt
1404,5254,inga,808,f,27.0,tt0072431,Young Frankenstein,1974,401.0,http://www.horrorlair.com/scripts/young.txt
1405,5254,medical student,199,m,NaN,tt0072431,Young Frankenstein,1974,401.0,http://www.horrorlair.com/scripts/young.txt
1406,5254,the monster,586,m,39.0,tt0072431,Young Frankenstein,1974,401.0,http://www.horrorlair.com/scripts/young.txt

In [22]:
grouped_ex_dialogue_df = extended_dialogue_df.groupby(['year', 'gender'])['words'].sum().reset_index()
grouped_ex_dialogue_df['date'] = grouped_ex_dialogue_df['year'].astype(str) + '-01-01'
grouped_ex_dialogue_df['date'] = pd.to_datetime(grouped_ex_dialogue_df['date'])
alt.Chart(grouped_ex_dialogue_df).mark_line().encode(
    x='date:T',
    y='words',
    color='gender'
).properties(
    title='Dialogue Over Time Colored By Gender (film_scripts)'
)

alt.Chart(...)

<h2> How could we tell if the amount of dialogue was increasing over time in movies? How might this influence the assessment about the breakdown of gender dialogue?

We can tell the amount of dialogue increased over time in movies by the graph provided above. Starting in 1990s, there was a dramatic increase of words in movies. Male characters had more dialogues than female characters over time.

<h2> How could test if there was any relationship between the filmâ€™s gross value and the amount of dialogue in the film?

In [27]:
merge_df = pd.merge(dialogue_df, film_scripts[['gross (inflation-adjusted)']], left_on='gross', right_on='gross (inflation-adjusted)', how='inner')
merge_df

,script_id,imdb_character_name,words,gender,age,imdb_id,title,year,gross,lines_data,gross (inflation-adjusted)
0,280,betty,311,f,35.0,tt0112579,The Bridges of Madison County,1995,142.0,4332023434343443203433434334433434343434434344...,142.0
1,280,carolyn johnson,873,f,NaN,tt0112579,The Bridges of Madison County,1995,142.0,4332023434343443203433434334433434343434434344...,142.0
2,280,eleanor,138,f,NaN,tt0112579,The Bridges of Madison County,1995,142.0,4332023434343443203433434334433434343434434344...,142.0
3,280,francesca johns,2251,f,46.0,tt0112579,The Bridges of Madison County,1995,142.0,4332023434343443203433434334433434343434434344...,142.0
4,280,madge,190,f,46.0,tt0112579,The Bridges of Madison County,1995,142.0,4332023434343443203433434334433434343434434344...,142.0
...,...,...,...,...,...,...,...,...,...,...,...
163621,5254,herr falkstein,158,m,69.0,tt0072431,Young Frankenstein,1974,401.0,7777721374572264357636646755234465233200247532...,401.0
163622,5254,igor,1072,m,40.0,tt0072431,Young Frankenstein,1974,401.0,7777721374572264357636646755234465233200247532...,401.0
163623,5254,inga,808,f,27.0,tt0072431,Young Frankenstein,1974,401.0,7777721374572264357636646755234465233200247532...,401.0
163624,5254,medical student,199,m,NaN,tt0072431,Young Frankenstein,1974,401.0,7777721374572264357636646755234465233200247532...,401.0
163625,5254,the monster,586,m,39.0,tt0072431,Young Frankenstein,1974,401.0,7777721374572264357636646755234465233200247532...,401.0

In [32]:
grouped_merge_df = merge_df.groupby(['gross (inflation-adjusted)'])['words'].sum().reset_index()
alt.Chart(grouped_merge_df).mark_line().encode(
    x='gross (inflation-adjusted):Q',
    y='words',
).properties(
    title='Dialogue Over Gross Value (film_scripts)'
)

alt.Chart(...)

Gross value is lower when there were more dialogues in the film.